"""empty message

Revision ID: 6f1c7328a0e8
Revises: 
Create Date: 2021-03-17 03:39:30.829164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f1c7328a0e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('number_of_bedrooms', sa.String(length=5), nullable=True),
    sa.Column('number_of_bathrooms', sa.String(length=5), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('price', sa.String(length=16), nullable=True),
    sa.Column('type', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('photo', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('properties')
    # ### end Alembic commands ###
